// <auto-generated />
using System;
using AgilityScore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgilityScore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251107124119_InitialAgilityScore")]
    partial class InitialAgilityScore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("AgilityScore.Models.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ChosenSpeedMps")
                        .HasColumnType("REAL");

                    b.Property<int>("EventDayId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LengthMeters")
                        .HasColumnType("REAL");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TRMFactor")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventDayId", "Level", "Size", "Type")
                        .IsUnique();

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("AgilityScore.Models.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Breed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Club")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HandlerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HandlerId");

                    b.HasIndex("Name");

                    b.ToTable("Dogs");
                });

            modelBuilder.Entity("AgilityScore.Models.EventDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Judge")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("EventDays");
                });

            modelBuilder.Entity("AgilityScore.Models.Handler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Handlers");
                });

            modelBuilder.Entity("AgilityScore.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DogId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dorsal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Eliminated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Faults")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Refusals")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("TimeReal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("DogId");

                    b.HasIndex("Dorsal");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("AgilityScore.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventDaysCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("AgilityScore.Models.Competition", b =>
                {
                    b.HasOne("AgilityScore.Models.EventDay", "EventDay")
                        .WithMany("Competitions")
                        .HasForeignKey("EventDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventDay");
                });

            modelBuilder.Entity("AgilityScore.Models.Dog", b =>
                {
                    b.HasOne("AgilityScore.Models.Handler", "Handler")
                        .WithMany("Dogs")
                        .HasForeignKey("HandlerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Handler");
                });

            modelBuilder.Entity("AgilityScore.Models.EventDay", b =>
                {
                    b.HasOne("AgilityScore.Models.Season", "Season")
                        .WithMany("EventDays")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("AgilityScore.Models.Participant", b =>
                {
                    b.HasOne("AgilityScore.Models.Competition", "Competition")
                        .WithMany("Participants")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgilityScore.Models.Dog", "Dog")
                        .WithMany("Participants")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Dog");
                });

            modelBuilder.Entity("AgilityScore.Models.Competition", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("AgilityScore.Models.Dog", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("AgilityScore.Models.EventDay", b =>
                {
                    b.Navigation("Competitions");
                });

            modelBuilder.Entity("AgilityScore.Models.Handler", b =>
                {
                    b.Navigation("Dogs");
                });

            modelBuilder.Entity("AgilityScore.Models.Season", b =>
                {
                    b.Navigation("EventDays");
                });
#pragma warning restore 612, 618
        }
    }
}
